apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: henvendelse-les
  namespace: default
  labels:
    team: personoversikt
spec:
  image: "docker.pkg.github.com/navikt/henvendelse-les/henvendelse-les:{{version}}"
  port: 8991
  team: personoversikt
  liveness:
    path: /henvendelse-les/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /henvendelse-les/isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://henvendelse-les.nais.preprod.local
    - https://modapp-q0.adeo.no/henvendelse-les
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /henvendelse-les/metrics
  vault:
    enabled: true
  env:
    - name: ISSO_JWKS_URL
      value: https://isso-q.adeo.no/isso/oauth2/connect/jwk_uri
    - name: ISSO_ISSUER
      value: https://isso-q.adeo.no:443/isso/oauth2