apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: henvendelse-les
  namespace: default
  labels:
    team: personoversikt
spec:
  image: {{ image }}
  port: 8991
  team: personoversikt
  liveness:
    path: /henvendelse-les/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /henvendelse-les/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /henvendelse-les/internal/metrics
  resources:
    limits:
      cpu: 200m
      memory: 192Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingresses:
    - https://henvendelse-les.nais.preprod.local
    - https://modapp-q0.adeo.no/henvendelse-les
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  vault:
    enabled: true
  env:
    - name: ISSO_JWKS_URL
      value: "https://isso-q.adeo.no/isso/oauth2/connect/jwk_uri"
    - name: ISSO_ISSUER
      value: "https://isso-q.adeo.no:443/isso/oauth2"
    - name: STS_JWKS_URL
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/jwks"
    - name: STS_ISSUER
      value: "https://security-token-service.nais.preprod.local"
